language: ruby
rvm:
  - 2.2.0
before_script:
  - cp config/database.example.yml config/database.yml
  - bundle exec rake db:create db:migrate db:test:prepare

addons:
  code_climate:
    repo_token: c58152c6e32fb07aa816fab7350bac1c827763c8bf2a5bdee145c00a01efcbbb
