source 'https://rubygems.org'

ruby '2.2.1'

gem 'alert_message'
gem 'bootstrap-sass', '~> 3.3.3'
gem 'carrierwave'
gem 'cancan'
gem 'coffee-rails'
gem 'cloudinary'
gem 'devise'
gem 'devise-bootstrap-views'
gem 'disqus_rails'
gem 'friendly_id'
gem 'gravatar-ultimate'
gem 'jbuilder', '~> 2.0'
gem 'jquery-rails'
gem 'jquery-turbolinks'
gem 'kaminari'
gem 'modernizr-rails'
gem 'meta-tags'
gem 'pg'
gem 'rails', '4.2.1'
gem 'rails-i18n'
gem 'rails_admin', git: 'git://github.com/luizpicolo/rails_admin.git'
gem 'randumb'
gem 'redcarpet'
gem 'sass-rails'
gem 'sprockets-rails', github: 'rails/sprockets-rails'
gem 'turbolinks'
gem 'uglifier', '>= 1.3.0'

group :development, :test do
  gem 'better_errors'
  gem 'binding_of_caller'
  gem 'capybara'
  gem 'codeclimate-test-reporter', require: nil
  gem 'database_rewinder'
  gem 'factory_girl_rails'
  gem 'faker'
  gem 'rspec-rails', '~> 3.1.0'
  gem 'selenium-webdriver'
  gem 'shoulda-matchers'
  gem 'spring'
end

group :production do
  gem 'passenger'
  gem 'therubyracer'
  gem 'rails_12factor'
end
