# production:
#   # Paths and URls
#   PATH_UPLOADS:   "/home/equipanan/public_html/railsapp/storage/"
#   #ASSETS_HOST:    "http://assets.equipanan.com.br"
#   UPLOAD_HOST:    "http://cdn1.equipanan.com.br/"
#
#   # Configuration mail
#   ADDRESS:    "mail.loginhost.com.br"
#   PORT:       "25"
#   DOMAIN:     ""
#   USER_NAME:  ""
#   PASSWORD:   ""
#
#   # Recipe mail
#   TO_MAIL: ""
#   FROM_MAIL: "contato@equipanan.com.br"
#
#   # Password ssh
#   SFTP_FOLDER: "public_html/railsapp/storage/"
#   SFTP_HOST: "storage.w3case.com.br"
#   SFTP_USER: ""
#   SFTP_PASSWORD: ""

# staging:
#   # Paths and URls
#   PATH_UPLOADS:   "/home/equipanan/public_html/railsapp/storage/"
#   ASSETS_HOST:    "http://10.0.1.114:8080"
#   UPLOAD_HOST:    "http://10.0.1.114:8081/"
#
#   # Configuration mail
#   ADDRESS:    "smtp.gmail.com"
#   PORT:       "587"
#   DOMAIN:     'gmail.com'
#   USER_NAME:  ''
#   PASSWORD:   ''
#
#   # Recipe mail
#   TO_MAIL: ""
#   FROM_MAIL: ""

development:
  # Paths and URls
  # PATH_UPLOADS:   "/home/equipanan/public_html/railsapp/storage/"
  # ASSETS_HOST:    "http://10.0.1.114:8080"
  # UPLOAD_HOST:    "http://10.0.1.114:8081/"

  # Configuration mail
  ADDRESS:    "smtp.gmail.com"
  PORT:       "587"
  DOMAIN:     'gmail.com'
  USER_NAME:  ''
  PASSWORD:   ''

  # Recipe mail
  TO_MAIL: "luizpicolo@w3case.com.br"
  FROM_MAIL: "luizpicolo@w3case.com.br"

  # Password ssh
  SFTP_FOLDER: "public_html/railsapp/storage/"
  SFTP_HOST: "storage.w3case.com.br"
  SFTP_USER: ""
  SFTP_PASSWORD: ""
