development: &dev
  adapter: mysql2
  encoding: utf8
  database: personal_page_dev
  pool: 5
  username: root
  password: root
  socket: /var/run/mysqld/mysqld.sock

test:
  adapter: postgresql
  encoding: unicode
  database: personal_page_test
  pool: 5
  username: postgres
  password:

production:
  <<: *dev
