development:
  host: localhost
  adapter: postgresql
  encoding: unicode
  database: personal_page
  pool: 5
  username: postgres
  password: postgres

test:
  host: localhost
  adapter: postgresql
  encoding: unicode
  database: personal_page
  pool: 5
  username: postgres
  password: postgres

production: &dev
